// <auto-generated />
using System;
using HomeStream.Infrastructure.Persistence.Implementation;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HomeStream.Infrastructure.Migrations
{
    [DbContext(typeof(HomeStreamDbContext))]
    partial class HomeStreamDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HomeStream.Domain.Entities.JobDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CancellationRequestOn")
                        .HasColumnType("bigint")
                        .HasColumnName("cancellation_request_on");

                    b.Property<long?>("CompletedOn")
                        .HasColumnType("bigint")
                        .HasColumnName("completed_on");

                    b.Property<long>("CreatedOn")
                        .HasColumnType("bigint")
                        .HasColumnName("created_on");

                    b.Property<string>("ExceptionMessage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("exception_message");

                    b.Property<bool>("IsCancellationRequested")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_cancellation_requested");

                    b.Property<string>("JobPayloadTypeName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("job_payload_type_name");

                    b.Property<string>("JobTypeName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("job_type_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<double>("Progress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValue(0.0)
                        .HasColumnName("progress");

                    b.Property<string>("StackTrace")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("stack_trace");

                    b.Property<long?>("StartedOn")
                        .HasColumnType("bigint")
                        .HasColumnName("started_on");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_job_details");

                    b.ToTable("job_details", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
